services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    environment:
      - 'OLLAMA_MODELS=gemma3:latest nomic-embed-text:latest'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'